### ISSUE TITLE
Build for a long time

### ISSUE THREAD

**Issue by Yeppppe** [bytedance/SchurVINS#4]
Does it normal that i spend more than 1 hour on building?

**Comment by xyh2211** [comment]
Has the compilation been successful?

**Comment by Yeppppe** [comment]
> Has the compilation been successful?

yep,i find  the problem is about dbow2_catkin,and i find the method on ''https://github.com/MIT-SPARK/dbow2_catkin'' which can accelerate build the dbow2_catkin!

**Comment by xyh2211** [comment]
Hello brother, how should I use this GitHub? I'm not very familiar with compiling.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月16日(星期二) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytedance/SchurVINS] Build for a long time (Issue #4)














  
Has the compilation been successful?
  
yep,i find  the problem is about dbow2_catkin,and i find the method on ''https://github.com/MIT-SPARK/dbow2_catkin'' which can accelerate build the dbow2_catkin!

**Comment by ymhy1314** [comment]
> Hello brother, how should I use this GitHub? I'm not very familiar with compiling.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月16日(星期二) 上午9:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bytedance/SchurVINS] Build for a long time (Issue #4) Has the compilation been successful? yep,i find the problem is about dbow2_catkin,and i find the method on ''https://github.com/MIT-SPARK/dbow2_catkin'' which can accelerate build the dbow2_catkin! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好catkin build编译过程中dbow2_catkin编译过久或者编译失败可以尝试这个办法（本人测试有效）：
1）把https://github.com/dorian3d/DBoW2 clone下来，把里面的文件 复制到your_catkin_ws/build/dbow2_catkin/dbow2_src-prefix/src/dbow2_src下（dbow2_src文件夹可能要自己创建）
2）将your_catkin_ws/src/dbow2_catkin/CMakeLists.txt 中的GIT_REPOSITORY https://github.com/dorian3d/DBoW2.git 注释掉
3）回到你的工作空间路径下，并重新catkin buil
